In [1]:
import numpy as np

# Learning the basics of numpy 

### Numpy is a very popular and varsatile python module used for scientific calculations and use of arrays. 

In [2]:
#Creating an array
x=np.array([12,34,56,78,90])

In [3]:
print(x)

[12 34 56 78 90]


In [4]:
#to check the dimention of the array
print(x.ndim) 

1


In [5]:
#tells the no. of rows and columns
print(x.shape) 

(5,)


In [6]:
#gives the size of array
print(x.size) 

5


In [7]:
#accessing the element of array
print(x[0]) 

12


In [8]:
#gives max no. in array
print(x.max()) 

90


In [9]:
#gives min no. in array
print(x.min()) 

12


In [10]:
print(x.sum()) #prints sum
print(x.prod()) #prints product
print(x.argmax()) #gives location of max no.
print(x.argmin()) #gives location of min no.

270
160392960
4
0


In [11]:
#Creating a 2D array
y=np.array([[21,43,65,87,97],[12,34,56,78,90]])

In [12]:
print(y)

[[21 43 65 87 97]
 [12 34 56 78 90]]


In [13]:
print(y.ndim)

2


In [14]:
print(y.shape)

(2, 5)


In [15]:
print(y.size)

10


In [16]:
#accessing any element of array, in this case accessing first element
print(y[0,0]) 

21


In [17]:
#changing the shape of array and note that this is "not" transposing
print(y.reshape(5,2)) 

[[21 43]
 [65 87]
 [97 12]
 [34 56]
 [78 90]]


In [18]:
#transposing the matrix
print(y.transpose()) 

[[21 12]
 [43 34]
 [65 56]
 [87 78]
 [97 90]]


In [19]:
#the no. of elements is different, hence is executed as two lists
z=np.array([[21,43,65,87,97],[34,56,78,90]]) 

In [20]:
print(z)

[list([21, 43, 65, 87, 97]) list([34, 56, 78, 90])]


In [21]:
print(z.size)

2


In [22]:
t=np.zeros([3,3]) # 3*3 zero matrix
print(t)
o=np.ones([3,3]) # 3*3 matrix of ones
print(o)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
#identity matrix of size 4
e=np.eye(4) 
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Slicing

In [24]:
#gives o/p as an array 
n=np.arange(12) 

In [25]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
n=n.reshape(3,4)

In [27]:
#[starting_row:end_row,starting_coln:end_coln]          note: end in slicing is not included
n[:,:]  

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
n[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [29]:
#first '3' is the no. of floors, second '3' is the no. of rows and '4' is the no. of columns
r=np.arange(36).reshape(3,3,4) 

In [30]:
r  #3d matrix

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [31]:
r[1:2,1:,2:]

array([[[18, 19],
        [22, 23]]])

In [32]:
a=np.arange(10).reshape(2,5)
b=np.arange(10).reshape(5,2)
c=np.dot(a,b)
c

array([[ 60,  70],
       [160, 195]])

In [36]:
#rsmallest interger function
print(np.ceil(45.4))  

46.0


In [37]:
#greatest integer function
print(np.floor(45.6)) 

45.0


In [38]:
#rounding off to nearest integer
print(np.round(45.6)) 

46.0
